### ISSUE TITLE
Warning and errors not reported

### ISSUE THREAD

**Issue by JEFworks** [Stuartlab-UCSC/monocle-docker#1]
Running method within R on simulated data resulted in this error:
```
write_common_json(monocle_obj, file=output)
Error in which_branch(path, mst_node_to_ids, branch_assignment) : 
  The branch finding method was indeterminant.
```

However, when I run via Docker:
```
docker run -v $(pwd)/data/:/data/ monocle run_method input.txt output.txt
```

I see a number of libraries being loaded, then `Removing 27 outliers` and then nothing happens. I do not get any warning or error messages. There is no `output.txt` in the `data` folder. It seems like the script just exists without warning. 

Is there a way to make error or warnings be displayed more explicitly with a try-catch or something?

**Comment by mrJeppard** [comment]
Hi Jean,

Hmmm, strange, yes I'll dig into this now. Could you respond with the entire text dump from running the docker container?

I gave it a spin on my machine, and it looks like there might be a monocle error halting the execution. I am running `./CASTING/topology1/prosstt0/prosstt0_simulation.txt`. I am curious if you have a: 
```
Error in round(CM) : non-numeric argument to mathematical function
Calls: monocle_analysis ... estimateSizeFactorsForMatrix -> estimateSizeFactorsForDenseMatrix
```  
Just before the 
```In addition: Warning messages:
1: In newCellDataSet(expression_matrix) :
  Warning: featureData must contain a column verbatim named 'gene_short_name' for certain functions
2: In newCellDataSet(expression_matrix) :
  Warning: featureData must contain a column verbatim named 'gene_short_name' for certain functions
3: In newCellDataSet(expression_matrix) :
  Warning: featureData must contain a column verbatim named 'gene_short_name' for certain functions
Execution halted
```

**Comment by JEFworks** [comment]
Hi Duncan,

One issue with the prosst simulation files from Niko is that they are formatted with rows as cells and columns as genes whereas monocle is expecting columns as cells and rows as genes. So if you are using the inputs made by Niko, they will need to be transposed.

Also, since the simulated data are counts, you will need to specify a count-based process in monocle:
```
cds <- newCellDataSet(expression_matrix, expressionFamily = negbinomial())
```

I've already made these modifications and can successfully run:
```
exp_mat <- read_data(input)
monocle_obj <- monocle_analysis(exp_mat)
plot_cell_trajectory(monocle_obj) # double check
```

I only get an error upon attempting to output the monocle object into your common json format. 
```
write_common_json(monocle_obj, file=output)
```

Specifically, the error can be traced back to this function call:
```
> branch.number <- which_branch(path, mst_node_to_ids, branch_assignment)
Error in which_branch(path, mst_node_to_ids, branch_assignment) : 
  The branch finding method was indeterminant.
```

The entire text dump from running the docker container is as follows, with no indication of errors, other than there being no output.txt in the data/ folder:
```
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker $  > docker run -v $(pwd)/data/:/data/ monocle run_method input.txt output.txt
Loading required package: Matrix
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:Matrix’:

    colMeans, colSums, rowMeans, rowSums, which

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: ggplot2
Loading required package: VGAM
Loading required package: stats4
Loading required package: splines
Loading required package: DDRTree
Loading required package: irlba
[1] "/data/input.txt"
Removing 27 outliers
```

**Comment by mrJeppard** [comment]
Okay several things going on here, thanks for the tips and feedback. 

For the error coming out of the `write_common_json` function, could you post an issue on [traj-converters](https://github.com/Stuartlab-UCSC/traj-converters) with a reference to the data causing the error? I have the simulated data on my machine so a relative path from the `./CASTING` directory will be sufficient.

As for the silent docker, it appears our docker images are different.

When you clone this repository and build the image, are you making sure there is a physical copy of the submodule on your machine? i.e. 
```
git clone https://github.com/Stuartlab-UCSC/monocle-docker.git && cd monocle-docker && git submodule update --init --recursive
docker build -t monocle .
```

And if you are doing that, are your local repo's up to date?

**Comment by JEFworks** [comment]
I just tried to reclone and rebuild. I still get the same issues with the same lack of error reporting:
```
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > ls
Dockerfile	README.md	data		src		traj-converters
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > docker run -v $(pwd)/data/:/data/ monocle run_method input.txt output.txt
Removing 27 outliers
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > cd data/
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker/data $  > ls
input.txt
```
Perhaps I have a Docker specific preference somewhere to suppress error messages?

I've attached the input.txt simulation file I'm using in case it is helpful. 
[input.txt](https://github.com/Stuartlab-UCSC/monocle-docker/files/2372225/input.txt)

**Comment by mrJeppard** [comment]
ah yes thanks for the input file.

This feels macitosh specific, perhaps something about the volume binding not being where you expect it to be. The latest is working on my linux box. With mac's, docker is running on a VM so there are added complications [I'm not familiar with](https://docs.docker.com/docker-for-mac/osxfs/)  yet. I suggest trying 1-3 below before diving into the link.

1.  Could you try to use the official image and see if you have the same problem? If this **works** then there is something different about your docker image build process.
```
docker pull stuartlab/monocle
docker run -v $(pwd)/data/:/data/ stuartlab/monocle run_method input.txt output.txt
ls data
```
On my machine I'm seeing a complaint about memory, but the output.txt file is present in the ./data dir.
```
Removing 27 outliers
 Warning message:
 system call failed: Cannot allocate memory 
ls data
input.txt output.txt
```


2. Are you able to write a file to the data directory from the docker at all? If this **doesn't work** then perhaps the script is running as it should but there's something fishy with the volume binding.
```
docker run -v $(pwd)/data:/data monocle /bin/touch /data/empty_file
ls data
# You should see an empty_file in the output
```
3. If you **do** see a ./data/empty_file then a more cumbersome way to test the same thing is executing the script from inside the container.
```
docker run -it -v $(pwd)/data:/data monocle /bin/bash
# Now you are inside the running container you should see a:
# root@8ac3057ef83a:/#  
# run the script and peak in the data dir:
run_method input.txt output.txt
ls /data
# Do you see it? Hopefully so.  If you don't see it I'm all out of ideas for now.
# Exit the container and see if its on your machine
exit
ls data
# If you don't see an output.txt then there's a volume binding issue.
```

**Comment by JEFworks** [comment]
Hi Duncan,

Thanks for the helpful suggestions. The issue is now resolved. I've detailed below the steps below for resolving the issue. 

Test 2 passed
```
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > docker run -v $(pwd)/data:/data monocle /bin/touch /data/empty_file
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > ls data
empty_file	input.txt
```

Test 3 failed (cryptic Killed message is returned)
```
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > docker run -it -v $(pwd)/data:/data monocle /bin/bash
root@05999ad5b80d:/# run_method input.txt output.txt
Removing 27 outliers
Killed
root@05999ad5b80d:/# exit
exit
```

Turns out, this is a [Mac specific issue](https://stackoverflow.com/questions/44417159/docker-process-killed-with-cryptic-killed-message).

I retried with a smaller file (only 1000 genes as opposed to 1000) and now it works.
```
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > docker run -it -v $(pwd)/data:/data monocle /bin/bash
root@51ea6c549b9e:/# run_method input_small.txt output_small.txt
Removing 27 outliers
root@51ea6c549b9e:/# exit
exit
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > ls data
input.txt		input_small.txt		output_small.txt
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > docker run -v $(pwd)/data/:/data/ monocle run_method input_small.txt output_small2.txt
Removing 27 outliers
Jean@Jeans-MacBook-Pro ~/Desktop/trajectory-test/monocle-docker2/monocle-docker $  > ls data/
input.txt		input_small.txt		output_small.txt	output_small2.txt
```

So the issue is memory related and the error reporting is apparently different on Mac vs. Windows.
